name: Deploy

on:
  push:
    branches: 
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
      
    - name: Install Neko
      run: sudo apt update && sudo apt install neko --yes
    
    - name: Download Haxe 4.0.5
      run: wget https://github.com/HaxeFoundation/haxe/releases/download/4.0.5/haxe-4.0.5-linux64.tar.gz
    
    - name: Extract Haxe
      run: tar xvf haxe-4.0.5-linux64.tar.gz
    
    - name: Add Haxe to path
      run: export PATH=$PATH:$(pwd)/haxe_20191217082701_67feacebc
    
    - name: Setup Haxelib
      run: haxelib setup haxelib
    
    - name: Install dependencies
      run: yes | haxelib install generate.hxml
    
    - name: Generate website
      run: haxe generate.hxml
    
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.2.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: out
